import { defineConfig } from "orval";

export default defineConfig({
	backend: {
		input: {
			target: "http://127.0.0.1:8080/openapi.json",
		},
		output: {
			mode: "tags-split",
			target: "./src/service/generated/api.ts",
			schemas: "./src/service/generated/model",
			client: "react-query",
			httpClient: "axios",
			formatter: "biome",
			override: {
				header: (info) =>
					[
						"// @ts-nocheck",
						"/**",
						" * Generated by Orval.",
						" * Do not edit manually.",
						` * ${info.title}`,
						` * OpenAPI spec version: ${info.version}`,
						" */",
						"",
					].join("\n"),
				mutator: {
					path: "./src/service/mutator/orval.ts",
					name: "customInstance",
				},
				query: {
					version: 5,
					useQuery: true,
					useMutation: true,
					shouldExportQueryKey: true,
				},
			},
		},
	},
});
